# Generated by Django 5.2.8 on 2025-11-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время завершения'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время начала работы'),
        ),
    ]
