# Generated by Django 5.2.8 on 2025-11-26 05:16

import django.db.models.deletion
from django.db import migrations, models


def create_corpuses_and_migrate_data(apps, schema_editor):
    Corpus = apps.get_model('tickets', 'Corpus')
    Ticket = apps.get_model('tickets', 'Ticket')
    
    # Создаем корпуса
    corpus_map = {}
    corpuses_data = [
        {'name': 'Главный корпус', 'number': 0},
        {'name': 'Корпус 1', 'number': 1},
        {'name': 'Корпус 2', 'number': 2},
        {'name': 'Корпус 3', 'number': 3},
        {'name': 'Корпус 4', 'number': 4},
        {'name': 'Корпус 5', 'number': 5},
        {'name': 'Корпус 6', 'number': 6},
        {'name': 'Корпус 7', 'number': 7},
        {'name': 'Корпус 8', 'number': 8},
        {'name': 'Корпус 9', 'number': 9},
    ]
    
    for data in corpuses_data:
        corpus, _ = Corpus.objects.get_or_create(
            name=data['name'],
            defaults={'number': data['number']}
        )
        corpus_map[data['name']] = corpus
    
    # Мигрируем существующие тикеты
    for ticket in Ticket.objects.all():
        corpus_name = getattr(ticket, 'corpus_old', None)  # старое строковое значение
        if corpus_name and corpus_name in corpus_map:
            ticket.corpus_new = corpus_map[corpus_name]
            ticket.save()
        elif corpus_name:
            # Если корпус не найден, создаем дефолтный
            default_corpus = corpus_map.get('Главный корпус')
            if default_corpus:
                ticket.corpus_new = default_corpus
                ticket.save()


def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_completed_at_ticket_started_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название корпуса')),
                ('number', models.IntegerField(blank=True, null=True, unique=True, verbose_name='Номер корпуса')),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпуса',
                'ordering': ['number', 'name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='corpus',
            field=models.ForeignKey(blank=True, help_text='Корпус для хелпдеска (оставьте пустым для учителей и админов)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='helpdesk_users', to='tickets.corpus', verbose_name='Корпус'),
        ),
        # Переименовываем старое поле
        migrations.RenameField(
            model_name='ticket',
            old_name='corpus',
            new_name='corpus_old',
        ),
        # Добавляем новое поле как nullable
        migrations.AddField(
            model_name='ticket',
            name='corpus_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets_new', to='tickets.corpus'),
        ),
        # Миграция данных
        migrations.RunPython(create_corpuses_and_migrate_data, reverse_migration),
        # Удаляем старое поле
        migrations.RemoveField(
            model_name='ticket',
            name='corpus_old',
        ),
        # Переименовываем новое поле
        migrations.RenameField(
            model_name='ticket',
            old_name='corpus_new',
            new_name='corpus',
        ),
        # Делаем поле обязательным
        migrations.AlterField(
            model_name='ticket',
            name='corpus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='tickets.corpus', verbose_name='Корпус'),
        ),
    ]
