# Generated by Django 5.2.8 on 2025-11-26 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_corpus_user_corpus_alter_ticket_corpus'),
    ]

    operations = [
    ]
