# Generated by Django 5.0.1 on 2025-11-29 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_migrate_corpus_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='cabinet',
            new_name='room',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='corpus',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='image',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='report_image',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='video',
        ),
        migrations.AddField(
            model_name='ticket',
            name='building',
            field=models.CharField(default='Main Building', max_length=100, verbose_name='Корпус'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_overdue',
            field=models.BooleanField(default=False, verbose_name='Просрочена'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='media_after',
            field=models.ImageField(blank=True, null=True, upload_to='tickets/after/', verbose_name='Фото (После)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='media_before',
            field=models.FileField(blank=True, null=True, upload_to='tickets/before/', verbose_name='Медиа (До)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='taken_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Взят в работу'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_checked_in',
            field=models.BooleanField(default=False, verbose_name='На смене'),
        ),
        migrations.AddField(
            model_name='user',
            name='plain_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пароль (raw)'),
        ),
        migrations.AddField(
            model_name='user',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало работы'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новая'), ('TRANSIT', 'В пути'), ('IN_PROGRESS', 'В работе'), ('WAITING_APPROVE', 'Ожидает подтверждения'), ('CLOSED', 'Закрыта'), ('UNFIXABLE', 'Неисправима')], default='NEW', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='tickets.ticket', verbose_name='Заявка')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
            },
        ),
    ]
