# Generated by Django 4.2.27 on 2026-02-02 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_rename_cabinet_ticket_room_remove_ticket_corpus_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_checked_in',
        ),
    ]
