# Generated by Django 4.2.27 on 2026-02-02 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_remove_user_is_checked_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='corpus',
        ),
    ]
