# Generated by Django 4.2.27 on 2026-02-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_remove_user_corpus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новая'), ('IN_PROGRESS', 'В работе'), ('WAITING_APPROVE', 'Ожидает подтверждения'), ('CLOSED', 'Закрыта'), ('UNFIXABLE', 'Неисправима')], default='NEW', max_length=20, verbose_name='Статус'),
        ),
    ]
