# Generated by Django 4.2.27 on 2026-02-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_alter_ticket_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_start_time', models.TimeField(default='09:00', verbose_name='Начало работы')),
                ('work_end_time', models.TimeField(default='18:00', verbose_name='Конец работы')),
                ('allow_outside_working_hours', models.BooleanField(default=False, verbose_name='Разрешить заявки вне рабочего времени')),
            ],
            options={
                'verbose_name': 'Настройка системы',
                'verbose_name_plural': 'Настройки системы',
            },
        ),
    ]
