# Generated by Django 4.2.27 on 2026-02-03 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_systemsetting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corpus',
            options={'ordering': ['id'], 'verbose_name': 'Корпус', 'verbose_name_plural': 'Корпуса'},
        ),
        migrations.RemoveField(
            model_name='corpus',
            name='number',
        ),
    ]
