# Generated by Django 4.2.27 on 2026-02-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_corpus_options_remove_corpus_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.EmailField(max_length=254, verbose_name='Кому')),
                ('template_type', models.CharField(max_length=50, verbose_name='Тип шаблона')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('status', models.CharField(choices=[('success', 'Успешно'), ('failed', 'Ошибка')], max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Лог письма',
                'verbose_name_plural': 'Логи писем',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('new_ticket', 'Новая заявка'), ('comment_added', 'Добавлен комментарий'), ('ticket_completed', 'Заявка выполнена'), ('ticket_overdue', 'Заявка просрочена')], max_length=50, unique=True, verbose_name='Тип уведомления')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('body', models.TextField(verbose_name='Текст письма (поддерживает HTML)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Шаблон письма',
                'verbose_name_plural': 'Шаблоны писем',
            },
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='email_from_address',
            field=models.EmailField(default='erkemyrzaa@gmail.com', max_length=254, verbose_name='Email отправителя'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='email_from_name',
            field=models.CharField(default='HelpDesk', max_length=100, verbose_name='Имя отправителя'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='notify_on_comment',
            field=models.BooleanField(default=True, verbose_name='Уведомлять о новом комментарии'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='notify_on_complete',
            field=models.BooleanField(default=True, verbose_name='Уведомлять о завершении заявки'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='notify_on_create',
            field=models.BooleanField(default=True, verbose_name='Уведомлять о новой заявке'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='notify_on_overdue',
            field=models.BooleanField(default=True, verbose_name='Уведомлять о просрочке'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='overdue_notification_email',
            field=models.EmailField(default='myrzabekerkebulanakt@gmail.com', max_length=254, verbose_name='Email для уведомлений о просрочке'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='smtp_host',
            field=models.CharField(default='smtp.gmail.com', max_length=100, verbose_name='SMTP Host'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=100, verbose_name='SMTP Password'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='smtp_port',
            field=models.IntegerField(default=587, verbose_name='SMTP Port'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False, verbose_name='Использовать SSL'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='smtp_use_tls',
            field=models.BooleanField(default=True, verbose_name='Использовать TLS'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='smtp_user',
            field=models.CharField(default='erkemyrzaa@gmail.com', max_length=100, verbose_name='SMTP User'),
        ),
    ]
