# Generated by Django 4.2.27 on 2026-02-04 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_emaillog_emailtemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('success', 'Успешно'), ('failed', 'Ошибка отправки (SMTP)'), ('queue_failed', 'Ошибка очереди (Redis)')], max_length=20, verbose_name='Статус'),
        ),
    ]
