# Generated by Django 4.2.27 on 2026-02-04 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_alter_emaillog_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailLog',
        ),
        migrations.DeleteModel(
            name='EmailTemplate',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='email_from_address',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='email_from_name',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='notify_on_comment',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='notify_on_complete',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='notify_on_create',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='notify_on_overdue',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='overdue_notification_email',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='smtp_host',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='smtp_password',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='smtp_port',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='smtp_use_ssl',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='smtp_use_tls',
        ),
        migrations.RemoveField(
            model_name='systemsetting',
            name='smtp_user',
        ),
    ]
