# Generated by Django 4.2.27 on 2026-02-04 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_delete_emaillog_delete_emailtemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новая'), ('IN_PROGRESS', 'В работе'), ('WAITING_FOR_PARTS', 'Ожидается запчасть'), ('CLOSED', 'Закрыта'), ('UNFIXABLE', 'Неисправима')], default='NEW', max_length=20, verbose_name='Статус'),
        ),
    ]
