# Generated by Django 4.2.27 on 2026-02-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='parts_wait_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина ожидания запчастей'),
        ),
    ]
