# Generated by Django 4.2.27 on 2026-02-05 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_alter_ticket_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='deadline',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('NEW', 'Новая'), ('IN_PROGRESS', 'В работе'), ('WAITING_FOR_PARTS', 'Ожидается запчасть'), ('CLOSED', 'Закрыта'), ('UNFIXABLE', 'Неисправима'), ('CANCELED', 'Отменена')], default='NEW', max_length=20, verbose_name='Статус'),
        ),
    ]
