# Generated by Django 4.2.27 on 2026-02-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_alter_ticket_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Фамилия и имя')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Имя пользователя (Login)')),
                ('password', models.CharField(max_length=128, verbose_name='Хэш пароля')),
                ('institute', models.CharField(choices=[('Ректорат', 'Ректорат'), ('Институт педагогики и традиционного искусства', 'Институт педагогики и традиционного искусства'), ('Институт естествознания', 'Институт естествознания'), ('Инженерно-технологический институт', 'Инженерно-технологический институт'), ('Институт экономики и права', 'Институт экономики и права'), ('Гуманитарно-педагогический институт', 'Гуманитарно-педагогический институт'), ('Институт искусственного интеллекта', 'Институт искусственного интеллекта')], max_length=255, verbose_name='Институт / подразделение')),
                ('position', models.CharField(max_length=255, verbose_name='Должность')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает решения'), ('APPROVED', 'Одобрено'), ('REJECTED', 'Отклонено')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Запрос на регистрацию',
                'verbose_name_plural': 'Запросы на регистрацию',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО'),
        ),
        migrations.AddField(
            model_name='user',
            name='institute',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Институт / подразделение'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность'),
        ),
    ]
