# Generated by Django 4.2.27 on 2026-02-05 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_registrationrequest_user_full_name_user_institute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationrequest',
            name='plain_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Пароль (raw)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='author_name_display',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя автора (отображение)'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
