# Generated by Django 4.2.27 on 2026-02-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_alter_feedback_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_viewed_by_admin',
            field=models.BooleanField(default=False, verbose_name='Просмотрено админом'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_viewed_by_admin',
            field=models.BooleanField(default=False, verbose_name='Просмотрено админом'),
        ),
    ]
