# Generated by Django 4.2.27 on 2026-02-05 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_feedback_is_viewed_by_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_viewed_by_admin',
        ),
        migrations.AddField(
            model_name='registrationrequest',
            name='is_viewed_by_admin',
            field=models.BooleanField(default=False, verbose_name='Просмотрен администратором'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='is_viewed_by_admin',
            field=models.BooleanField(default=False, verbose_name='Просмотрен администратором'),
        ),
    ]
