# Generated by Django 4.2.27 on 2026-02-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_remove_ticket_is_viewed_by_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_hidden_by_author',
            field=models.BooleanField(default=False, verbose_name='Скрыта автором'),
        ),
    ]
