# Generated by Django 4.2.27 on 2026-02-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_ticket_is_hidden_by_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='is_hidden_by_author',
        ),
        migrations.AddField(
            model_name='ticket',
            name='hidden_at_by_author',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Скрыто пользователем'),
        ),
    ]
