# Generated by Django 4.2.27 on 2026-02-09 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_remove_ticket_is_hidden_by_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assistants',
            field=models.ManyToManyField(blank=True, related_name='assisted_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Помощники'),
        ),
        migrations.CreateModel(
            name='TicketAssistOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Ожидает'), ('ACCEPTED', 'Принято'), ('DECLINED', 'Отклонено'), ('CANCELED', 'Отменено')], default='PENDING', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата ответа')),
                ('from_helpdesk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_assist_offers', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assist_offers', to='tickets.ticket', verbose_name='Заявка')),
                ('to_helpdesk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_assist_offers', to=settings.AUTH_USER_MODEL, verbose_name='Получатель')),
            ],
            options={
                'verbose_name': 'Предложение помощи',
                'verbose_name_plural': 'Предложения помощи',
                'unique_together': {('ticket', 'to_helpdesk', 'status')},
            },
        ),
    ]
